python SmoothPursuitClassification.py -s=../dataset/zhegallo/01-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/01-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/02-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/02-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/03-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/03-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/04-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/05-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/05-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/06-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/07-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/07-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/08-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/08-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/09-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/09-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/10-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/10-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/11-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/11-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/12-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/12-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/13-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/13-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/14-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/14-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/15-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/15-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/16-1Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/16-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/18-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/19-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/20-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/21-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn
python SmoothPursuitClassification.py -s=../dataset/zhegallo/22-2Settings.xml --smooth=savgol --algo=ivt --classifier=fasterrcnn